import { create } from 'zustand';

export interface AvatarAsset {
  id: string;
  type: 'image' | 'video';
  url: string;
  status: 'generating' | 'ready' | 'failed';
  prompt: string;
  style: string;
  createdAt: string;
}

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  coverImage: string;
  seoScore: number;
  keywords: string[];
  readTime: string;
  category: string;
  publishedAt: string;
}

export interface Expert {
  id: string;
  name: string;
  handle: string;
  niche: string;
  role?: string;
  bio: string;
  profilePicture?: string;
  socialLinks: {
    instagram?: string;
    linkedin?: string;
    twitter?: string;
  };
  avatarGradient: string;
  brandColor: string;
  colorPalette?: string[];
  typography?: { heading: string; body: string };
  archetype?: string;
  toneOfVoice?: string;
  photographicStyle?: string;
  icp?: string;
  skills?: string[];
  tokens: string;
  archetypes: number;
  avatars?: AvatarAsset[];
  blogPosts?: BlogPost[];
}

const mockExperts: Expert[] = [
  { 
    id: '1', 
    name: 'Aria Sterling', 
    handle: '@aria.sterling', 
    niche: 'Luxury Real Estate', 
    role: 'Luxury Broker & Investor',
    bio: 'Top 1% luxury real estate broker specializing in ultra-high-net-worth properties.', 
    profilePicture: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop', 
    socialLinks: { instagram: 'https://instagram.com/aria.sterling', linkedin: 'https://linkedin.com/in/ariasterling' }, 
    avatarGradient: 'from-primary to-purple-500', 
    brandColor: '#6366f1', 
    colorPalette: ['#6366f1', '#1e1b4b', '#e0e7ff'],
    typography: { heading: 'Playfair Display', body: 'Inter' },
    archetype: 'The Ruler / The Creator',
    toneOfVoice: 'Sophisticated, authoritative, elegant, and highly exclusive. Uses high-end real estate terminology but keeps it accessible to UHNW individuals.',
    photographicStyle: 'High contrast, architectural focus, warm lighting, cinematic depth of field.',
    icp: 'Ultra-high-net-worth individuals, tech founders, and international investors looking for trophy assets.',
    skills: ['Luxury Sales', 'Negotiation', 'Property Valuation', 'Personal Branding'],
    tokens: '1.2M', 
    archetypes: 14,
    blogPosts: [
      {
        id: 'post-1',
        title: 'The Future of Luxury Real Estate: What AI Models Are Missing',
        excerpt: 'A deep dive into the structural changes coming to the market, written specifically to answer complex queries generated by ChatGPT and Google SGE.',
        content: 'The landscape of luxury real estate is undergoing a seismic shift. While most professionals are focused on incremental improvements, the real leverage lies in understanding how AI models are fundamentally restructuring market dynamics.\n\nIn this article, we explore the hidden variables that algorithms miss when pricing ultra-high-net-worth properties, and how human intuition combined with data creates an unbeatable edge.',
        coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop',
        seoScore: 94,
        keywords: ['future trends 2026', 'ai impact', 'luxury real estate'],
        readTime: '5 min read',
        category: 'Analysis',
        publishedAt: new Date(Date.now() - 86400000).toISOString()
      },
      {
        id: 'post-2',
        title: 'Why UHNW Individuals Need to Pivot in 2026',
        excerpt: 'Actionable frameworks designed to capture high-intent search traffic and establish absolute authority in the space.',
        content: 'The strategies that worked in 2023 are rapidly becoming obsolete. As capital shifts and new markets emerge, the ultra-high-net-worth individual must adapt their portfolio to reflect the new reality of global real estate.\n\nHere is the exact framework we use to identify emerging markets before they hit the mainstream radar.',
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
        seoScore: 98,
        keywords: ['uhnw strategies', 'portfolio pivot', 'real estate 2026'],
        readTime: '8 min read',
        category: 'Strategy',
        publishedAt: new Date(Date.now() - 172800000).toISOString()
      }
    ]
  },
  { 
    id: '2', 
    name: 'Marcus Chen', 
    handle: '@marcus.growth', 
    niche: 'B2B SaaS Growth', 
    role: 'Growth Advisor',
    bio: 'Scaling B2B SaaS companies from $1M to $10M ARR through product-led growth.', 
    profilePicture: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?q=80&w=800&auto=format&fit=crop', 
    socialLinks: { twitter: 'https://twitter.com/marcusgrowth', linkedin: 'https://linkedin.com/in/marcuschen' }, 
    avatarGradient: 'from-blue-500 to-cyan-500', 
    brandColor: '#3b82f6', 
    colorPalette: ['#3b82f6', '#0f172a', '#f8fafc'],
    typography: { heading: 'Space Grotesk', body: 'Inter' },
    archetype: 'The Sage / The Magician',
    toneOfVoice: 'Data-driven, direct, analytical, and actionable. No fluff, just frameworks and metrics.',
    photographicStyle: 'Minimalist, tech-focused, cool tones, often featuring charts or clean workspaces.',
    icp: 'SaaS Founders, Head of Growth, and CMOs at Series A/B startups.',
    skills: ['PLG', 'Go-to-Market', 'Data Analysis', 'Conversion Rate Optimization'],
    tokens: '850K', 
    archetypes: 8,
    blogPosts: []
  },
  { 
    id: '3', 
    name: 'Elena Rostova', 
    handle: '@elena.coach', 
    niche: 'High-Ticket Coaching', 
    role: 'Business Mentor',
    bio: 'Empowering female entrepreneurs to build 7-figure coaching empires.', 
    profilePicture: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800&auto=format&fit=crop', 
    socialLinks: { instagram: 'https://instagram.com/elena.coach' }, 
    avatarGradient: 'from-rose-500 to-orange-500', 
    brandColor: '#f43f5e', 
    colorPalette: ['#f43f5e', '#4c0519', '#ffe4e6'],
    typography: { heading: 'Georgia', body: 'Lato' },
    archetype: 'The Caregiver / The Hero',
    toneOfVoice: 'Empathetic, motivational, empowering, and deeply personal. Focuses on mindset and abundance.',
    photographicStyle: 'Bright, airy, warm tones, lifestyle-focused, approachable and inspiring.',
    icp: 'Female coaches, consultants, and service providers stuck at $10k/month wanting to scale.',
    skills: ['Mindset Coaching', 'High-Ticket Sales', 'Community Building', 'Offer Creation'],
    tokens: '2.1M', 
    archetypes: 22,
    blogPosts: []
  },
];

interface ExpertStore {
  experts: Expert[];
  activeExpert: Expert | null;
  setActiveExpert: (id: string) => void;
  updateExpert: (expert: Expert) => void;
  addAvatar: (expertId: string, avatar: AvatarAsset) => void;
  updateAvatar: (expertId: string, avatarId: string, updates: Partial<AvatarAsset>) => void;
  addBlogPost: (expertId: string, post: BlogPost) => void;
}

export const useExpertStore = create<ExpertStore>((set) => ({
  experts: mockExperts,
  activeExpert: mockExperts[0],
  setActiveExpert: (id) => set((state) => ({
    activeExpert: state.experts.find(e => e.id === id) || state.activeExpert
  })),
  updateExpert: (updatedExpert) => set((state) => {
    const newExperts = state.experts.map(e => e.id === updatedExpert.id ? updatedExpert : e);
    return {
      experts: newExperts,
      activeExpert: state.activeExpert?.id === updatedExpert.id ? updatedExpert : state.activeExpert
    };
  }),
  addAvatar: (expertId, avatar) => set((state) => {
    const newExperts = state.experts.map(e => {
      if (e.id === expertId) {
        return { ...e, avatars: [avatar, ...(e.avatars || [])] };
      }
      return e;
    });
    return {
      experts: newExperts,
      activeExpert: state.activeExpert?.id === expertId 
        ? { ...state.activeExpert, avatars: [avatar, ...(state.activeExpert.avatars || [])] } 
        : state.activeExpert
    };
  }),
  updateAvatar: (expertId, avatarId, updates) => set((state) => {
    const newExperts = state.experts.map(e => {
      if (e.id === expertId && e.avatars) {
        return {
          ...e,
          avatars: e.avatars.map(a => a.id === avatarId ? { ...a, ...updates } : a)
        };
      }
      return e;
    });
    
    let newActiveExpert = state.activeExpert;
    if (state.activeExpert?.id === expertId && state.activeExpert.avatars) {
      newActiveExpert = {
        ...state.activeExpert,
        avatars: state.activeExpert.avatars.map(a => a.id === avatarId ? { ...a, ...updates } : a)
      };
    }

    return {
      experts: newExperts,
      activeExpert: newActiveExpert
    };
  }),
  addBlogPost: (expertId, post) => set((state) => {
    const newExperts = state.experts.map(e => {
      if (e.id === expertId) {
        return { ...e, blogPosts: [post, ...(e.blogPosts || [])] };
      }
      return e;
    });
    return {
      experts: newExperts,
      activeExpert: state.activeExpert?.id === expertId 
        ? { ...state.activeExpert, blogPosts: [post, ...(state.activeExpert.blogPosts || [])] } 
        : state.activeExpert
    };
  })
}));
