import { useState } from 'react';
import { useExpertStore, BlogPost } from '@/store/expertStore';
import { Globe, Search, Sparkles, ArrowUpRight, LayoutTemplate, FileText, Wand2, CheckCircle2, X } from 'lucide-react';

export function ExpertBlog() {
  const { activeExpert, addBlogPost } = useExpertStore();
  const [activeTab, setActiveTab] = useState<'preview' | 'seo-settings'>('preview');
  const [isGenerating, setIsGenerating] = useState(false);
  const [showGenerationModal, setShowGenerationModal] = useState(false);
  const [generatedPost, setGeneratedPost] = useState<any>(null);
  const [viewingPost, setViewingPost] = useState<BlogPost | null>(null);

  if (!activeExpert) {
    return <div className="p-8 text-text-main">Please select an expert first.</div>;
  }

  const handleGeneratePost = (contextPost?: BlogPost) => {
    setShowGenerationModal(true);
    setIsGenerating(true);
    setGeneratedPost(null);

    // Simulate AI generation process
    setTimeout(() => {
      setIsGenerating(false);
      setGeneratedPost({
        title: contextPost ? `Expanded: ${contextPost.title}` : `The Future of ${activeExpert.niche.split(' ')[0] || 'Industry'}: What AI Models Are Missing`,
        seoScore: 98,
        keywords: ['future trends 2026', 'ai impact', activeExpert.niche.toLowerCase()],
        excerpt: `A deep dive into the structural changes coming to the market, written specifically to answer complex queries generated by ChatGPT and Google SGE.`,
        content: `The landscape of ${activeExpert.niche} is undergoing a seismic shift. While most professionals are focused on incremental improvements, the real leverage lies in understanding how AI models are fundamentally restructuring market dynamics.\n\nIn this article, we explore the hidden variables that algorithms miss when pricing assets and evaluating opportunities. Human intuition, when paired with the right data, creates an unbeatable edge that AI alone cannot replicate.\n\nHere is the exact framework we use to identify emerging trends before they hit the mainstream radar, ensuring our clients are always one step ahead.`
      });
    }, 4000);
  };

  const handlePublish = () => {
    if (!generatedPost) return;

    const newPost: BlogPost = {
      id: Math.random().toString(36).substring(7),
      title: generatedPost.title,
      excerpt: generatedPost.excerpt,
      content: generatedPost.content,
      coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=2070&auto=format&fit=crop', // AI placeholder image
      seoScore: generatedPost.seoScore,
      keywords: generatedPost.keywords,
      readTime: '4 min read',
      category: 'Strategy',
      publishedAt: new Date().toISOString()
    };

    addBlogPost(activeExpert.id, newPost);
    setShowGenerationModal(false);
    setGeneratedPost(null);
  };

  return (
    <div className="p-8 h-full flex flex-col text-text-main overflow-hidden relative">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-8 gap-4 shrink-0">
        <div>
          <h1 className="font-serif text-2xl mb-1">SEO & Public Portal</h1>
          <p className="text-text-muted text-sm">Manage the AI-optimized landing page and blog for <span className="font-semibold" style={{ color: activeExpert.brandColor }}>{activeExpert.name}</span>.</p>
        </div>
        <div className="flex items-center gap-4 flex-wrap">
          <div className="flex bg-surface border border-border rounded-lg p-1">
            <button 
              onClick={() => setActiveTab('preview')}
              className={`px-4 py-1.5 rounded text-sm font-medium transition-colors ${activeTab === 'preview' ? 'bg-white/10 text-white' : 'text-text-muted hover:text-text-main'}`}
            >
              Live Preview
            </button>
            <button 
              onClick={() => setActiveTab('seo-settings')}
              className={`px-4 py-1.5 rounded text-sm font-medium transition-colors ${activeTab === 'seo-settings' ? 'bg-white/10 text-white' : 'text-text-muted hover:text-text-main'}`}
            >
              AEO / SEO Settings
            </button>
          </div>
          <button className="text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-colors hover:brightness-110 w-full sm:w-auto justify-center" style={{ backgroundColor: activeExpert.brandColor }}>
            <Globe size={16} />
            Publish Changes
          </button>
        </div>
      </div>

      {activeTab === 'preview' ? (
        <div className="flex-1 overflow-hidden flex flex-col bg-bg border border-border rounded-2xl shadow-2xl relative">
          {/* Browser Chrome */}
          <div className="h-12 bg-surface border-b border-border flex items-center px-4 gap-4 shrink-0">
            <div className="flex gap-1.5">
              <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-500/80"></div>
              <div className="w-3 h-3 rounded-full bg-green-500/80"></div>
            </div>
            <div className="flex-1 bg-bg border border-border rounded-md h-7 flex items-center px-3 text-xs text-text-muted font-mono justify-center">
              https://{activeExpert.name.toLowerCase().replace(/\s+/g, '')}.expertos.com
            </div>
            <div className="w-12"></div>
          </div>

          {/* Page Content */}
          <div className="flex-1 overflow-y-auto bg-white text-gray-900 custom-scrollbar">
            {/* Hero Section */}
            <div className="relative py-20 px-12 overflow-hidden" style={{ backgroundColor: `${activeExpert.brandColor}0A` }}>
              <div className="absolute top-0 right-0 w-96 h-96 rounded-full blur-3xl -translate-y-1/2 translate-x-1/4 opacity-50" style={{ backgroundColor: activeExpert.brandColor }}></div>
              <div className="max-w-4xl mx-auto relative z-10 flex flex-col md:flex-row items-center gap-8 md:gap-12">
                <div className="flex-1">
                  <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider mb-6" style={{ backgroundColor: `${activeExpert.brandColor}1A`, color: activeExpert.brandColor }}>
                    <Sparkles size={14} /> Official Portal
                  </div>
                  <h1 className="text-3xl md:text-5xl font-serif font-bold mb-4 text-gray-900 leading-tight">{activeExpert.name}</h1>
                  <h2 className="text-xl text-gray-600 mb-6 font-medium">{activeExpert.niche}</h2>
                  <p className="text-gray-600 leading-relaxed mb-8 max-w-2xl">
                    {activeExpert.bio || `Leading expert in ${activeExpert.niche}. Helping ${activeExpert.icp || 'professionals'} achieve excellence through proven frameworks and deep industry insights.`}
                  </p>
                  <button className="px-8 py-3 rounded-lg text-white font-bold transition-transform hover:scale-105" style={{ backgroundColor: activeExpert.brandColor }}>
                    Work with {activeExpert.name.split(' ')[0]}
                  </button>
                </div>
                <div className="w-32 h-32 md:w-64 md:h-64 shrink-0 rounded-full overflow-hidden border-4 border-white shadow-2xl order-first md:order-last">
                  {activeExpert.profilePicture ? (
                    <img src={activeExpert.profilePicture} alt={activeExpert.name} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full bg-gradient-to-br flex items-center justify-center" style={{ backgroundImage: `linear-gradient(to bottom right, ${activeExpert.brandColor}, #000)` }}>
                      <span className="text-6xl font-bold text-white">{activeExpert.name.charAt(0)}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Articles Section */}
            <div className="py-16 px-12 max-w-5xl mx-auto">
              <div className="flex justify-between items-end mb-10">
                <div>
                  <h3 className="text-3xl font-serif font-bold text-gray-900 mb-2">Latest Insights</h3>
                  <p className="text-gray-500">Optimized for AI Search Engines (AEO) & Google</p>
                </div>
                <button className="text-sm font-bold flex items-center gap-1" style={{ color: activeExpert.brandColor }}>
                  View All <ArrowUpRight size={16} />
                </button>
              </div>

              {(!activeExpert.blogPosts || activeExpert.blogPosts.length === 0) ? (
                <div className="text-center py-12 bg-gray-50 rounded-2xl border border-gray-200">
                  <FileText size={48} className="mx-auto text-gray-300 mb-4" />
                  <h4 className="text-lg font-bold text-gray-900 mb-2">No Insights Published Yet</h4>
                  <p className="text-gray-500 text-sm mb-6 max-w-md mx-auto">Use the AI Blog Generator to create optimized content based on market research and news.</p>
                  <button 
                    onClick={() => handleGeneratePost()}
                    className="text-sm font-bold flex items-center gap-2 text-white px-6 py-3 rounded-xl transition-colors hover:brightness-110 mx-auto" 
                    style={{ backgroundColor: activeExpert.brandColor }}
                  >
                    <Wand2 size={16} /> Generate First Post
                  </button>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  {activeExpert.blogPosts.map((post) => (
                    <div key={post.id} className="group cursor-pointer flex flex-col" onClick={() => setViewingPost(post)}>
                      <div className="aspect-video rounded-xl bg-gray-100 mb-4 overflow-hidden relative">
                        <img src={post.coverImage} alt={post.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                        <div className="absolute top-3 left-3 bg-white/90 backdrop-blur-sm px-2 py-1 rounded text-[10px] font-bold uppercase tracking-wider text-gray-900 flex items-center gap-1">
                          <Sparkles size={12} className="text-purple-500" /> AEO Optimized
                        </div>
                      </div>
                      <div className="flex gap-2 mb-3">
                        <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-1 rounded bg-gray-100 text-gray-600">{post.category}</span>
                        <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-1 rounded bg-gray-100 text-gray-600">{post.readTime}</span>
                      </div>
                      <h4 className="text-xl font-bold text-gray-900 mb-2 group-hover:text-primary transition-colors">{post.title}</h4>
                      <p className="text-gray-600 text-sm line-clamp-2 mb-4 flex-1">{post.excerpt}</p>
                      <div className="flex items-center gap-3 mt-auto">
                        <button 
                          onClick={(e) => { e.stopPropagation(); setViewingPost(post); }}
                          className="text-sm font-bold flex items-center gap-1 text-gray-900 hover:text-primary transition-colors"
                        >
                          Read Full <ArrowUpRight size={16} />
                        </button>
                        <button 
                          onClick={(e) => { e.stopPropagation(); handleGeneratePost(post); }}
                          className="text-sm font-bold flex items-center gap-1 text-white px-3 py-1.5 rounded-lg transition-colors hover:brightness-110" 
                          style={{ backgroundColor: activeExpert.brandColor }}
                        >
                          <Wand2 size={14} /> Generate Blog Post
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto custom-scrollbar">
          <div className="max-w-4xl mx-auto space-y-6">
            <div className="bg-surface border border-border rounded-2xl p-6">
              <h3 className="text-lg font-serif mb-4 flex items-center gap-2">
                <Search className="text-primary" /> AI Engine Optimization (AEO) Status
              </h3>
              <p className="text-sm text-text-muted mb-6">
                These settings control how Large Language Models (like ChatGPT, Claude) and AI Overviews (Google SGE) perceive and cite {activeExpert.name}.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
                <div className="bg-bg border border-border rounded-xl p-4">
                  <div className="text-2xl font-bold text-green-400 mb-1">94/100</div>
                  <div className="text-xs text-text-muted uppercase tracking-wider font-bold">Entity Authority</div>
                </div>
                <div className="bg-bg border border-border rounded-xl p-4">
                  <div className="text-2xl font-bold text-blue-400 mb-1">12</div>
                  <div className="text-xs text-text-muted uppercase tracking-wider font-bold">Target Keywords</div>
                </div>
                <div className="bg-bg border border-border rounded-xl p-4">
                  <div className="text-2xl font-bold text-purple-400 mb-1">Active</div>
                  <div className="text-xs text-text-muted uppercase tracking-wider font-bold">Schema Markup</div>
                </div>
              </div>

              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-bold uppercase tracking-wider text-text-muted mb-2">Core Entity Definition (For LLMs)</label>
                  <textarea 
                    className="w-full bg-bg border border-border rounded-xl p-4 text-sm text-text-main focus:outline-none focus:border-primary min-h-[100px]"
                    defaultValue={`${activeExpert.name} is a leading authority in ${activeExpert.niche}. Known for ${activeExpert.archetypes}, they primarily serve ${activeExpert.icp}. Their core methodology involves...`}
                  />
                  <p className="text-[10px] text-text-muted mt-1">This text is injected into the site's hidden schema to train AI crawlers on exactly who this expert is.</p>
                </div>
              </div>
            </div>

            <div className="bg-surface border border-border rounded-2xl p-6">
              <h3 className="text-lg font-serif mb-4 flex items-center gap-2">
                <LayoutTemplate className="text-primary" /> Automated Blog Pipeline
              </h3>
              <p className="text-sm text-text-muted mb-6">
                The Orchestrator agent automatically drafts SEO-optimized articles based on trending topics in the Market Research tab.
              </p>

              <div className="space-y-3">
                <div className="flex items-center justify-between p-3 bg-bg border border-border rounded-xl">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-green-500/10 text-green-500 flex items-center justify-center">
                      <FileText size={16} />
                    </div>
                    <div>
                      <div className="text-sm font-medium">The Scarcity Premium in 2026</div>
                      <div className="text-[10px] text-text-muted">Status: Published • 1.2k impressions</div>
                    </div>
                  </div>
                  <button className="text-xs text-primary hover:underline">Edit</button>
                </div>
                <div className="flex items-center justify-between p-3 bg-bg border border-border rounded-xl">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-yellow-500/10 text-yellow-500 flex items-center justify-center">
                      <FileText size={16} />
                    </div>
                    <div>
                      <div className="text-sm font-medium">Why AI Won't Replace High-End Advisory</div>
                      <div className="text-[10px] text-text-muted">Status: In Review by QA Agent</div>
                    </div>
                  </div>
                  <button className="text-xs text-primary hover:underline">Review</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* AI Generation Modal */}
      {showGenerationModal && (
        <div className="absolute inset-0 z-50 flex items-center justify-center p-8 bg-bg/80 backdrop-blur-sm">
          <div className="bg-surface border border-border rounded-2xl shadow-2xl w-full max-w-3xl overflow-hidden flex flex-col max-h-full">
            <div className="p-4 border-b border-border flex justify-between items-center bg-bg">
              <div className="flex items-center gap-2">
                <Wand2 size={18} style={{ color: activeExpert.brandColor }} />
                <h3 className="font-bold">AI Blog Generator</h3>
              </div>
              <button onClick={() => setShowGenerationModal(false)} className="p-2 hover:bg-white/5 rounded-lg text-text-muted transition-colors">
                <X size={20} />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto custom-scrollbar">
              {isGenerating ? (
                <div className="flex flex-col items-center justify-center py-20">
                  <div className="w-20 h-20 rounded-2xl bg-bg border border-border flex items-center justify-center mb-6 shadow-xl relative overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-white/5 to-transparent animate-[shimmer_2s_infinite]"></div>
                    <Wand2 size={40} className="animate-pulse" style={{ color: activeExpert.brandColor }} />
                  </div>
                  <h4 className="text-xl font-serif mb-3">Orchestrator Prime is writing...</h4>
                  <p className="text-sm text-text-muted text-center max-w-md leading-relaxed">
                    Analyzing target keywords, applying {activeExpert.name}'s tone of voice, and structuring the article for maximum AEO (AI Engine Optimization) impact.
                  </p>
                </div>
              ) : generatedPost ? (
                <div className="space-y-6">
                  <div className="bg-green-500/10 border border-green-500/20 rounded-xl p-4 flex items-start gap-3">
                    <CheckCircle2 size={20} className="text-green-500 shrink-0 mt-0.5" />
                    <div>
                      <h4 className="text-sm font-bold text-green-500 mb-1">Blog Post Generated Successfully</h4>
                      <p className="text-xs text-green-400/80 leading-relaxed">The article has been optimized for search intent and aligned with the expert's core methodology.</p>
                    </div>
                  </div>

                  <div className="bg-bg border border-border rounded-xl p-6">
                    <div className="flex items-center justify-between mb-4">
                      <h2 className="text-2xl font-serif font-bold">{generatedPost.title}</h2>
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-bold uppercase tracking-wider text-green-400 bg-green-400/10 px-2 py-1 rounded">
                          SEO Score: {generatedPost.seoScore}
                        </span>
                      </div>
                    </div>
                    
                    <div className="flex gap-2 mb-6">
                      {generatedPost.keywords.map((kw: string, i: number) => (
                        <span key={i} className="text-[10px] font-bold uppercase tracking-wider bg-surface border border-border px-2 py-1 rounded text-text-muted">
                          {kw}
                        </span>
                      ))}
                    </div>

                    <div className="prose prose-invert max-w-none">
                      <p className="text-lg font-medium text-text-main mb-4">{generatedPost.excerpt}</p>
                      <div className="text-text-muted leading-relaxed whitespace-pre-wrap">{generatedPost.content}</div>
                    </div>
                  </div>

                  <div className="flex gap-3 pt-4 border-t border-border">
                    <button 
                      onClick={() => setShowGenerationModal(false)}
                      className="flex-1 bg-bg border border-border hover:bg-white/5 py-3 rounded-xl text-sm font-bold transition-colors"
                    >
                      Discard
                    </button>
                    <button 
                      onClick={handlePublish}
                      className="flex-[2] py-3 rounded-xl text-sm font-bold transition-colors text-white flex items-center justify-center gap-2 hover:brightness-110" 
                      style={{ backgroundColor: activeExpert.brandColor }}
                    >
                      <Globe size={16} /> Publish to Blog
                    </button>
                  </div>
                </div>
              ) : null}
            </div>
          </div>
        </div>
      )}

      {/* View Post Modal */}
      {viewingPost && (
        <div className="absolute inset-0 z-50 flex items-center justify-center p-8 bg-bg/80 backdrop-blur-sm">
          <div className="bg-surface border border-border rounded-2xl shadow-2xl w-full max-w-4xl overflow-hidden flex flex-col max-h-full">
            <div className="p-4 border-b border-border flex justify-between items-center bg-bg">
              <div className="flex items-center gap-2">
                <FileText size={18} style={{ color: activeExpert.brandColor }} />
                <h3 className="font-bold">Published Article</h3>
              </div>
              <button onClick={() => setViewingPost(null)} className="p-2 hover:bg-white/5 rounded-lg text-text-muted transition-colors">
                <X size={20} />
              </button>
            </div>
            
            <div className="p-8 overflow-y-auto custom-scrollbar bg-white text-gray-900">
              <div className="max-w-3xl mx-auto">
                <div className="flex gap-2 mb-4">
                  <span className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded bg-gray-100 text-gray-600">{viewingPost.category}</span>
                  <span className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded bg-gray-100 text-gray-600">{viewingPost.readTime}</span>
                  <span className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded bg-green-100 text-green-700">SEO: {viewingPost.seoScore}</span>
                </div>
                
                <h1 className="text-4xl font-serif font-bold mb-6 leading-tight">{viewingPost.title}</h1>
                
                <div className="flex items-center gap-3 mb-8">
                  <img src={activeExpert.profilePicture} alt={activeExpert.name} className="w-10 h-10 rounded-full object-cover" />
                  <div>
                    <div className="text-sm font-bold">{activeExpert.name}</div>
                    <div className="text-xs text-gray-500">{new Date(viewingPost.publishedAt).toLocaleDateString()}</div>
                  </div>
                </div>

                <img src={viewingPost.coverImage} alt={viewingPost.title} className="w-full aspect-video object-cover rounded-2xl mb-8 shadow-lg" />
                
                <div className="prose prose-lg max-w-none text-gray-700">
                  <p className="text-xl font-medium text-gray-900 mb-6 leading-relaxed">{viewingPost.excerpt}</p>
                  <div className="whitespace-pre-wrap leading-relaxed">{viewingPost.content}</div>
                </div>
                
                <div className="mt-12 pt-8 border-t border-gray-200">
                  <h4 className="text-sm font-bold uppercase tracking-wider text-gray-500 mb-3">Target Keywords</h4>
                  <div className="flex gap-2">
                    {viewingPost.keywords.map((kw, i) => (
                      <span key={i} className="text-xs font-bold bg-gray-100 text-gray-600 px-3 py-1.5 rounded-full">
                        {kw}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
